---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: 'Merge: oam-oam-controller'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

concurrency:
  # yamllint disable-line rule:line-length
  #group: compose-make-merge-${{ github.workflow }}-${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JDK_VERSION: "21"
  MVN_VERSION: "3.9.6"
  MAKE_TARGETS: "deploy"
  PUSH_NEXUS: true
  ENV_VARS: ${{ toJSON(vars) }}
  ARTIFACT_DIR:

jobs:
  maven-merge:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # - uses: lfit/checkout-gerrit-change-action@54d751e8bd167bc91f7d665dabe33fae87aaaa63 # v0.9
      #   with:
      #     gerrit-refspec: ${{ inputs.GERRIT_REFSPEC }}
      #     gerrit-url: ${{ vars.GERRIT_URL }}
      #     delay: "0s"

      - name: Run Maven
        # yamllint disable-line rule:line-length
        uses: ravipendurty/releng-reusable-workflows/.github/actions/make-build-action@main # main
        with:
          jdk-version: ${{ env.JDK_VERSION }}
          mvn-version: ${{ env.MVN_VERSION }}
          make-targets: ${{ env.MAKE_TARGETS }}

      - name: Sign artifacts
        # yamllint disable-line rule:line-length
        uses: modeseven-lfreleng-actions/sigul-sign-docker@initial-update  # Testing
        # Though inputs.SIGUL_SIGN is defined as a boolean, there is an issue
        # with inputs always being strings. Therefore we will only run if the
        # input is defined as string 'true.'
        # See https://github.com/actions/runner/issues/1483
        if: ${{ inputs.SIGUL_SIGN == 'true' }}
        with:
          sign-type: "sign-data"
          sign-object: ${{ env.ARTIFACT_DIR }}
          sigul-key-name: ${{ secrets.SIGUL_KEY }}
          gh-key: ${{ secrets.GHA_TOKEN }}
          sigul-ip: ${{ secrets.SIGUL_IP }}
          sigul-uri: ${{ secrets.SIGUL_URI }}
          sigul-conf: ${{ secrets.SIGUL_CONF }}
          sigul-pass: ${{ secrets.SIGUL_PASS }}
          sigul-pki: ${{ secrets.SIGUL_PKI }}

      - name: Push build
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: release-artifact
          path: ${{ env.ARTIFACT_DIR }}

  publish-nexus:
    needs: maven-merge
    if: ${{ inputs.PUSH_NEXUS == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Pull build
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: release-artifact
          path: "${{ env.ARTIFACT_DIR }}"

      - name: Publish to Nexus
        # yamllint disable-line rule:line-length
        uses: lfit/nexus-upload-action@977af1a1db8719876f12ed6d83fa453fcabb2f7a # v0.1.8
        with:
          nexus_server: ${{ vars.NEXUS_SERVER }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_repository: ${{ env.NEXUS_REPO }}
          upload_directory: ${{ env.ARTIFACT_DIR }}

  publish-artifactory:
    needs: maven-merge
    if: ${{ inputs.PUSH_ARTIFACTORY == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Pull build
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: release-artifact
          path: "${{ env.ARTIFACT_DIR }}"

      - name: Install jfrog cli
        # yamllint disable-line rule:line-length
        uses: jfrog/setup-jfrog-cli@ff5cb544114ffc152db9cea1cd3d5978d5074946 # v4.5.11
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Publish to Artifactory
        run: |
          jf rt upload ${{ env.ARTIFACT_DIR }} \
          ${{ vars.ARTIFACTORY_PATH }} \
          ${{ inputs.JFROG_OPTIONS }}

  publish-central:
    needs: maven-merge
    if: ${{ inputs.PUSH_CENTRAL == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Pull build
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: release-artifact
          path: "${{ env.ARTIFACT_DIR }}"

      - name: Publish to Maven Central
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/nexus-publish-action@977af1a1db8719876f12ed6d83fa453fcabb2f7a # v0.1.8
        with:
          nexus_server: ${{ vars.CENTRAL_SERVER }}
          nexus_username: ${{ secrets.CENTRAL_USERNAME }}
          nexus_password: ${{ secrets.CENTRAL_PASSWORD }}
          nexus_repository: ${{ env.NEXUS_REPO }}
          upload_directory: ${{ env.ARTIFACT_DIR }}
